# Generated by Django 4.1.4 on 2023-11-03 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField( null=True, upload_to=''),
        ),
    ]
